name: Prepare `release` branch

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Optional commit hash'
        required: false

jobs:
  prepare-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out `main` branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW }}

      - name: Set commit hash
        run: |
          if [ -z "${{ github.event.inputs.commit_hash }}" ]; then
            echo "COMMIT_HASH=$(git rev-parse origin/main)" >> $GITHUB_ENV
          else
            if ! git merge-base --is-ancestor ${{ github.event.inputs.commit_hash }} origin/main; then
              echo 'Error: invalid commit hash'
              exit 1
            fi
            echo "COMMIT_HASH=${{ github.event.inputs.commit_hash }}" >> $GITHUB_ENV
          fi

      - name: Update `release` branch
        run: |
          git checkout release
          git reset --hard $COMMIT_HASH
          git push -f origin release
